//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lecture_13
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMainUrl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMainUrl()
        {
            this.FetchTimeMS = 0;
            this.CompressionPercent = 100;
        }
    
        public string UrlHash { get; set; }
        public string Url { get; set; }
        public System.DateTime DiscoverDate { get; set; }
        public short LinkDepthLevel { get; set; }
        public System.DateTime LastCrawlingDate { get; set; }
        public string SourceCode { get; set; }
        public string ParentUrlHash { get; set; }
        public int FetchTimeMS { get; set; }
        public string PageTile { get; set; }
        public byte CompressionPercent { get; set; }
        public bool IsCrawled { get; set; }
        public string HostUrl { get; set; }
        public byte CrawlTryCounter { get; set; }
    }
}
